src/apps/organizations/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.LowerCaseConverter, "lowerc_slug")

app_name = "organizations"

urlpatterns = [
    path("", views.List.as_view(), name="index"),
    path("list/", views.List.as_view(), name="list"),
    path("map/", views.Map.as_view(), name="map"),
    path(
        "submit/",
        views.OrganzationSubmitWizardView.as_view(),
        name="submit-organization",
    ),
    path(
        "dashboard/",
        views.AdminDashboard.as_view(),
        name="dashboard",
    ),
    path(
        "promote/",
        views.PromotedOrganizations.as_view(),
        name="promote",
    ),
    path("popup/", views.Popup.as_view(), name="popup"),
    path(
        "<lowerc_slug:slug>/",
        views.OrganizationDetail.as_view(),
        name="show",
    ),
    path(
        "<lowerc_slug:slug>/edit/",
        views.OrganizationUpdate.as_view(),
        name="edit-organiziation",
    ),
    path(
        "<lowerc_slug:slug>/edit/services/",
        views.ServiceUpdate.as_view(),
        name="edit-services",
    ),
    path(
        "<lowerc_slug:slug>/edit/contacts/",
        views.ContactUpdate.as_view(),
        name="edit-contacts",
    ),
    path("access/<str:key>/", views.SharedPage.as_view(), name="sharedPage"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from apps.organizations.sitemap import OrganizationSitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap


urlpatterns = [
    path("admin/", admin.site.urls),
    path("filters/", include("apps.filtercategories.urls")),
    path("", include("apps.organizations.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("accounts/", include("apps.accounts.urls")),
    path("locations/", include("apps.locations.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("apps.theme.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "organizations": OrganizationSitemap,
                "flatpages": FlatPageSitemap,
            }
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/organizations/views.py
from django.http.response import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.utils.translation import gettext as _
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.vary import vary_on_headers
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import resolve, reverse
from django.db.models import Count, OuterRef, Subquery
from django.contrib.gis.serializers.geojson import Serializer
from apps.accounts.forms import OptionalSignUpForm
from apps.locations.models import PhysicalLocation
from apps.flatpages_parler.models import ParlerFlatPage
from apps.organizations.filters import ServiceFilter
from apps.organizations.models import Organization, Service, ShareKey, EmailContact
from apps.organizations.forms import OrganizationForm, ContactFormSet, ServicesFormSet
from apps.organizations.create_share import create_share_key
from apps.organizations.wizard_utils import handle_user_creation, handle_email_dispatch

from itertools import groupby
from django_fsm import TransitionNotAllowed
from formtools.wizard.views import SessionWizardView
from django_fsm_log.models import StateLog
from datetime import datetime

import os
import csv
import json


class SharedPage(View):
    """A page shared via a ShareKey."""

    def dispatch(self, request, key, *args, **kwargs):  # noqa: D102
        if ShareKey.objects.filter(pk=key).exists():
            shareKey = ShareKey.objects.get(pk=key)
            if shareKey.expired:
                raise Http404(_("Sharelink expired"))
            func, args, kwargs = resolve(shareKey.location)
            kwargs["shared"] = True
            return func(request, *args, **kwargs)
        else:
            raise Http404(_("Could not find the shared entry"))


class Filter(View):
    """Abstract view to filter the services."""

    container_template = ""
    data_template = ""

    def filter(self, request):
        """Filter the services and group them by organizations."""
        services_list = (
            Service.objects.all()
            .filter(organization__state="approved")
            .order_by("-organization__updated_at", "organization")
            .prefetch_related("organization")
        )

        service_filter = ServiceFilter(request.GET, queryset=services_list)
        group = groupby(service_filter.qs, lambda x: x.organization)
        grouped_services = [(k, list(e)) for (k, e) in group]

        self.context = {
            "filter": service_filter,
            "results": grouped_services,
        }

    def respond(self, request):
        """Render the response to the filter request, depending on the htmx target.

        none: Render the full page, including filter and results in current view
        results-container: Render the container of the current view including the data
        results-data: Only render the results data of current view
        """
        if request.htmx.target == "results-data":
            return render(request, self.data_template, self.context)

        elif request.htmx.target == "results-container":
            return render(
                request,
                self.container_template,
                {**self.context, "data_template": self.data_template},
            )

        else:
            return render(
                request,
                "filter/filter.html",
                {
                    **self.context,
                    "container_template": self.container_template,
                    "data_template": self.data_template,
                },
            )


class List(Filter):
    """List view of the filtered services."""

    container_template = "filter/list_container.html"
    data_template = "filter/list_data.html"

    @vary_on_headers("HX-Request")
    def get(self, request):  # noqa: D102
        super().filter(request)
        paginator = Paginator(self.context["results"], settings.PAGINATION_PER_PAGE)
        page = request.GET.get("page")

        try:
            results = paginator.page(page)
            results.paginator.page_range_elided = (
                results.paginator.get_elided_page_range(page, on_each_side=1, on_ends=1)
            )
        except PageNotAnInteger:
            results = paginator.page(1)
            results.paginator.page_range_elided = (
                results.paginator.get_elided_page_range(1, on_each_side=1, on_ends=1)
            )
        except EmptyPage:
            results = paginator.page(paginator.num_pages)
            results.paginator.page_range_elided = (
                results.paginator.get_elided_page_range(
                    paginator.num_pages, on_each_side=1, on_ends=1
                )
            )

        try:
            welcome_text = ParlerFlatPage.objects.get(url="/welcome/")
        except ObjectDoesNotExist:
            welcome_text = None

        self.context["welcome_text"] = welcome_text
        self.context["page"] = page
        self.context["results"] = results

        return super().respond(request)


class Map(Filter):
    """Map view of the filtered services."""

    container_template = "filter/map_container.html"
    data_template = "filter/map_data.html"

    @vary_on_headers("HX-Request")
    def get(self, request):  # noqa: D102
        super().filter(request)

        location_serializer = Serializer()
        geo_json = location_serializer.serialize(
            PhysicalLocation.objects.filter(
                id__in=self.context["filter"].qs.values("physicallocations")
            ).distinct(),
            geometry_field="coordinates",
            fields=[],
        )
        geo_json = json.loads(geo_json)
        # Add the services ids to the geo_json
        for feature in geo_json["features"]:
            feature["properties"]["services"] = list(
                self.context["filter"]
                .qs.filter(physicallocations=feature["id"])
                .values_list("id", flat=True)
            )
        no_physical_locations_qs = self.context["filter"].qs.filter(
            physicallocations=None
        )
        if no_physical_locations_qs.exists():
            geo_json["non_physical_locations"] = no_physical_locations_qs.count()
        self.context["results"] = geo_json

        return super().respond(request)


class OrganizationDetail(View):
    """Detail view for organization."""

    template_name = "organizations/show.html"

    def get(self, request, slug, *args, **kwargs):  # noqa: D102
        geo_json = None
        try:
            organization = Organization.objects.prefetch_related(
                "contacts",
                "topics",
                "services",
                "services__features",
                "services__classifications",
            ).get(slug__iexact=slug)
            if PhysicalLocation.objects.filter(
                services__organization=organization
            ).exists():
                # Get all locations of services from organization
                location_serializer = Serializer()
                geo_json = location_serializer.serialize(
                    PhysicalLocation.objects.filter(
                        services__organization=organization
                    ).distinct(),
                    geometry_field="coordinates",
                    fields=[],
                )
                geo_json = json.loads(geo_json)
                # Add the services ids to the geo_json
                for feature in geo_json["features"]:
                    feature["properties"]["services"] = list(
                        organization.services.filter(
                            physicallocations=feature["id"]
                        ).values_list("id", flat=True)
                    )
        except Organization.DoesNotExist:
            raise Http404(_("Organization does not exist"))

        if organization.state == "approved":
            return render(
                request,
                self.template_name,
                {
                    "organization": organization,
                    "services_physicallocations": geo_json,
                },
            )
        elif (
            organization.can_update(request.user)
            or kwargs.get("shared", None) is not None
        ):
            context = {
                "organization": organization,
                "services_physicallocations": geo_json,
            } | kwargs
            return render(request, self.template_name, context)
        else:
            raise PermissionDenied

    def post(self, request, slug, *args, **kwargs):  # noqa: D102
        data = request.POST
        if request.user.is_superuser or self.kwargs.get("shared", None):
            org = get_object_or_404(Organization, slug__iexact=slug)
            if data.get("approve"):
                try:
                    org.approve()
                    org.save()
                    messages.success(
                        request,
                        _("'%(org_name)s' was published.") % {"org_name": org.name},
                    )
                    return redirect(request.path)
                except TransitionNotAllowed:
                    messages.error(
                        request,
                        _("'%(org_name)s' could not be published.")
                        % {"org_name": org.name},
                    )
                    return redirect(org)
            elif data.get("account_url"):
                signup_key = create_share_key(

src/apps/organizations/templates/organizations/_edit_organization_header.html
{% load i18n %}
<div class="md:flex md:items-center md:justify-between">
    <div class="flex-1 min-w-0">
        <h2 class="text-2xl font-bold leading-7 sm:text-3xl sm:truncate">{{ organization.name }}</h2>
    </div>
    <div class="mt-4 flex md:mt-0 md:ml-4">
        <a href="{{ organization.get_absolute_url }}"
           class="inline-flex items-center px-4 py-2 rounded-md shadow-sm text-sm font-medium bg-primary-800 hover:bg-primary-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-800">
            <svg class="-ml-1 mr-2 h-5 w-5"
                 xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            {% translate "View" %}
        </a>
    </div>
</div>
<div class="mt-2">
    <div class="sm:hidden">
        <label for="tabs" class="sr-only">{% translate "Select a tab" %}</label>
        <select id="tabs"
                name="tabs"
                class="block w-full focus:ring-indigo-500 focus:border-indigo-500 rounded-md"
                onChange="if(this.value) window.location.href = this.value">
            <option {% if not "/services/" in request.path and not "/contacts/" in request.path %}selected{% endif %}
                    value="{{ organization.get_absolute_url }}edit/">{% translate "Organization data" %}</option>
            <option {% if "/services/" in request.path %}selected{% endif %}
                    value="{{ organization.get_absolute_url }}edit/services/">{% translate "Services" %}</option>
            <option {% if "/contacts/" in request.path %}selected{% endif %}
                    value="{{ organization.get_absolute_url }}edit/contacts/">{% translate "Contacts" %}</option>
        </select>
    </div>
    <div class="hidden sm:block">
        <div class="border-b border-gray-200">
            <nav class="-mb-px flex space-x-8" aria-label="Tabs">
                <a href="{{ organization.get_absolute_url }}edit/" class="{% if not "/services/" in request.path and not "/contacts/" in request.path %}border-primary-800 text-primary-800{% else %}border-transparent text-base-content/60 hover:text-base-content hover:border-gray-300{% endif %} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
                    {% translate "Organization data" %}
                </a>
                <a href="{{ organization.get_absolute_url }}edit/services/" class="{% if "/services/" in request.path %}border-primary-800 text-primary-800{% else %}border-transparent text-base-content/60 hover:text-base-content hover:border-gray-300{% endif %} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm" aria-current="page">{% translate "Services" %}</a>
                <a href="{{ organization.get_absolute_url }}edit/contacts/" class="{% if "/contacts/" in request.path %}border-primary-800 text-primary-800{% else %}border-transparent text-base-content/60 hover:text-base-content hover:border-gray-300{% endif %} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm" aria-current="page">{% translate "Contacts" %}</a>
            </nav>
        </div>
    </div>
</div>

src/apps/organizations/templates/organizations/_empty_organization_list.html
{% load i18n %}
<div class="text-lg bg-base-100 shadow rounded-lg border-primary-800 border-2 ">
    <div class="flex items-center px-4 py-4 sm:px-6">{% translate "No organizations found!" %}</div>
</div>

src/apps/organizations/templates/organizations/_filtercategories.html
{% load i18n %}
<div>
    {% if model.languages.first %}
        <div class="p-2 flex flex-row">
            <div class="pl-2 pr-4">
                <div class="sr-only">{% translate "Languages" %}</div>
                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-5 w-5"
                     fill="none"
                     viewBox="0 0 24 24"
                     stroke="currentColor"
                     stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 016.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129" />
                </svg>
            </div>
            <div>
                {% for language in model.languages.all %}
                    {# djlint:off #}
                    {{ language.name }}{% if not forloop.last %},{% endif %}
                    {# djlint:on #}
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {% if model.features.first %}
        <div class="p-2 flex flex-row">
            <div class="pl-2 pr-4">
                <div class="sr-only">{% translate "Accessibility" %}</div>
                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-5 w-5"
                     viewBox="0 0 20 20"
                     fill="currentColor">
                    <path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z" />
                </svg>
            </div>
            <div>
                {% for feature in model.features.all %}
                    {# djlint:off #}
                    {{ feature.name }}{% if not forloop.last %},{% endif %}
                    {# djlint:on #}
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {% if model.classifications.first %}
        <div class="p-2 flex flex-row">
            <div class="pl-2 pr-4">
                <div class="sr-only">{% translate "Classifications" %}</div>
                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-5 w-5"
                     viewBox="0 0 20 20"
                     fill="currentColor">
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                </svg>
            </div>
            <div>
                {% for classification in model.classifications.all %}
                    {# djlint:off #}
                    {{ classification.name }}{% if not forloop.last %},{% endif %}
                    {# djlint:on #}
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>

src/apps/organizations/templates/organizations/_organization.html
{# This template generates an organization entry in the search results list #}
{% load i18n %}
<div x-data
     class="bg-base-100 overflow-hidden rounded-lg divide-y divide-primary-800 border-primary-800 border-2 hover:border-primary-400 hover:divide-primary-400">
    <a href="{% url "organizations:show" organization.slug %}">
        <div class="flex items-center p-2 bg-primary-800 hover:bg-primary-400">
            {% if organization.logo %}
                <div class="flex-shrink-0 mr-4">
                    <img class="max-h-16 max-w-40 object-contain rounded object-left"
                         height="48"
                         width="auto"
                         src="{{ organization.logo.url }}"
                         alt="Logo of {{ organization.name }}"
                         loading="lazy">
                </div>
            {% endif %}
            <h3 class="text-lg leading-6 font-bold text-white mt-auto py-2 {% if not organization.logo %}pl-2{% endif %}"
                dir="auto">
                {{ organization.name }}
                {% if organization.superorganization %}
                    {% if organization.superorganization.alternative_name %}
                        [{{ organization.superorganization.alternative_name }}]
                    {% else %}
                        [{{ organization.superorganization.name }}]
                    {% endif %}
                {% endif %}
            </h3>
        </div>
    </a>
    <ul role="list">
        {% for service in services %}
            {% if forloop.counter0 < 3 %}
                {% include "organizations/partials/service_item.html" with collapsed=False %}
            {% else %}
                {% if forloop.counter0 == 3 %}
                    <ul data-less-services-text="{% translate "Show less services" %}"
                        data-more-services-text="{% translate "Show" %} {{ services|length|add:-3 }} {% translate "more service(s)" %}"
                        {# djlint:off #}
                        x-data="{
                            lessServicesText: $el.dataset.lessServicesText,
                            moreServicesText: $el.dataset.moreServicesText,
                            show: false
                        }"
                        {# djlint:on #}
                        class="divide-y divide-primary-800">
                    {% endif %}
                    {% include "organizations/partials/service_item.html" with collapsed=True %}
                    {% if forloop.last %}
                        <li x-cloak
                            hidden-no-js
                            class="px-6 py-2 border-0"
                            @click="show = ! show">
                            <div class="cursor-pointer hover:text-primary-800"
                                 x-text="show ? lessServicesText : moreServicesText">
                                {% trans "Further Services:" %}
                            </div>
                        </li>
                    </ul>
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
</div>

src/apps/organizations/templates/organizations/_welcome_entry.html
{% load i18n %}
{% load markdownify %}
{% load parler_tags %}
<div class="bg-base-100 rounded-lg divide-y divide-secondary-800 border-secondary-800 border-2"
     x-data="{ welcome: true }"
     x-show="welcome">
    <div class="flex items-center p-4 bg-secondary-800">
        <h3 class="text-lg leading-6 font-bold text-white">{{ welcome_text.title_translated | markdownify }}</h3>
        <button class="ml-auto text-white" @click="welcome = false">
            <span class="sr-only">Close</span>
            {% include 'icons/x-mark.html' with stroke_width=2 %}
        </button>
    </div>
    <div class="welcome-entry divide-y divide-secondary-800">{{ welcome_text.content_translated | markdownify }}</div>
</div>

src/apps/organizations/templates/organizations/create_contact.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="px-3 md:px-0 mx-auto mt-4">
        {% include "organizations/_edit_organization_header.html" with organization=organization %}
        <div class="flex items-center justify-center px-4 sm:px-6 md:px-0">
            <form method="post" enctype="multipart/form-data" class="mt-6 w-full">
                {% csrf_token %}
                {{ formset }}
                <div class="mt-4">{% include "partials/button.html" with label=_("Submit") %}</div>
            </form>
        </div>
    </div>
{% endblock %}

src/apps/organizations/templates/organizations/edit_organization.html
{% extends "base.html" %}
{% load i18n %}
{% load customtag %}
{% block content %}
    <div class="mx-auto px-3 md:px-0 mt-4">
        {% include "organizations/_edit_organization_header.html" with organization=organization %}
        <div class="flex items-center justify-center">
            <form method="post" enctype="multipart/form-data" class="mt-6 w-full">
                {% csrf_token %}
                {% include "partials/form_fields.html" with form=form help_text=True %}
                <br>
                {% include "partials/button.html" with label=_("Submit") %}
            </form>
        </div>
    </div>
{% endblock content %}

src/apps/organizations/templates/organizations/edit_services.html
{% extends "base.html" %}
{% load i18n %}
{% load customtag %}
{% block content %}
    <div class="px-3 md:px-0 mx-auto mt-4">
        {% include "organizations/_edit_organization_header.html" with organization=organization %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ formset }}
            <br>
            {% include "partials/button.html" with label=_("Submit") %}
        </form>
    </div>
{% endblock content %}