src/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from .views import (
    SignUpView,
    CustomLoginView,
    ProfileUpdateView,
    CustomPasswordChangeView,
    CustomPasswordResetView,
    AccountDeleteView,
    ProfileOrganizationsView,
)
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("signup/<slug>/", SignUpView.as_view(), name="signup"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "profile/",
        ProfileUpdateView.as_view(),
        name="profile",
    ),
    path(
        "organizations/",
        ProfileOrganizationsView.as_view(),
        name="profile_organizations",
    ),
    path(
        "password_change/",
        CustomPasswordChangeView.as_view(template_name="accounts/password_change.html"),
        name="password_change",
    ),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "delete",
        AccountDeleteView.as_view(template_name="accounts/delete.html"),
        name="delete",
    ),
]

src/apps/organizations/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.LowerCaseConverter, "lowerc_slug")

app_name = "organizations"

urlpatterns = [
    path("", views.List.as_view(), name="index"),
    path("list/", views.List.as_view(), name="list"),
    path("map/", views.Map.as_view(), name="map"),
    path(
        "submit/",
        views.OrganzationSubmitWizardView.as_view(),
        name="submit-organization",
    ),
    path(
        "dashboard/",
        views.AdminDashboard.as_view(),
        name="dashboard",
    ),
    path(
        "promote/",
        views.PromotedOrganizations.as_view(),
        name="promote",
    ),
    path("popup/", views.Popup.as_view(), name="popup"),
    path(
        "<lowerc_slug:slug>/",
        views.OrganizationDetail.as_view(),
        name="show",
    ),
    path(
        "<lowerc_slug:slug>/edit/",
        views.OrganizationUpdate.as_view(),
        name="edit-organiziation",
    ),
    path(
        "<lowerc_slug:slug>/edit/services/",
        views.ServiceUpdate.as_view(),
        name="edit-services",
    ),
    path(
        "<lowerc_slug:slug>/edit/contacts/",
        views.ContactUpdate.as_view(),
        name="edit-contacts",
    ),
    path("access/<str:key>/", views.SharedPage.as_view(), name="sharedPage"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from apps.organizations.sitemap import OrganizationSitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap


urlpatterns = [
    path("admin/", admin.site.urls),
    path("filters/", include("apps.filtercategories.urls")),
    path("", include("apps.organizations.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("accounts/", include("apps.accounts.urls")),
    path("locations/", include("apps.locations.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("apps.theme.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "organizations": OrganizationSitemap,
                "flatpages": FlatPageSitemap,
            }
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/accounts/models.py
# from django.db import models

# Create your models here.

src/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
)
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
from django.utils.decorators import method_decorator
from honeypot.decorators import check_honeypot


@method_decorator(check_honeypot, name="check_honeypot")
class SignUpForm(UserCreationForm):  # noqa: D101
    email = forms.EmailField(required=True)
    usable_password = None

    class Meta:  # noqa: D106
        model = User
        fields = ["username", "email", "password1", "password2"]

    def check_honeypot(self, request):  # noqa: D102
        return True

    def clean_email(self):  # noqa: D102
        email = User.objects.normalize_email(self.cleaned_data["email"]).lower()
        if email and User.objects.filter(email=email).exists():
            raise ValidationError(_("A user with this email already exists."))
        return email


class OptionalSignUpForm(SignUpForm):
    """Used in the submit wizard to optionally create a user account."""

    template_name = "accounts/forms/optional_signup_form.html"

    def __init__(self, *args, **kwargs):  # noqa: D107
        super().__init__(*args, **kwargs)
        self.label_suffix = ""  # Removes : as label suffix
        self.fields["username"].required = False
        self.fields["username"].help_text = _(
            "150 characters or fewer. Letters, digits and @/./+/-/_ only."
        )
        self.fields["email"].required = False
        self.fields["password1"].required = False
        self.fields["password2"].required = False

    class Meta(SignUpForm.Meta):  # noqa: D106
        include = ["member"]

    member = forms.BooleanField(
        label=_("I am a member of the submitted organization."),
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "opt-submit-checkbox"}),
    )

    def clean(self):
        """Validate input.

        Because all fields are optional if ANY field was filled in
        we must throw an ValidationError if not ALL other fields have been filled in.
        """
        cleaned_data_values = [
            self.cleaned_data.get("username"),
            self.cleaned_data.get("email"),
            self.cleaned_data.get("password1"),
            self.cleaned_data.get("password2"),
            # Don't check member field
        ]

        if any(cleaned_data_values) and not all(cleaned_data_values):
            raise ValidationError(_("Some fields are missing or have errors."))


class LoginForm(AuthenticationForm):  # noqa: D101
    username = forms.CharField(max_length=150, required=True, widget=forms.TextInput())
    password = forms.CharField(
        max_length=150, required=True, widget=forms.PasswordInput()
    )

    class Meta:  # noqa: D106
        model = User
        fields = ["username", "password"]


class ProfileUpdateForm(forms.ModelForm):  # noqa: D101
    username = forms.CharField(max_length=150, required=True, widget=forms.TextInput())
    email = forms.EmailField(max_length=150, required=True, widget=forms.TextInput())

    class Meta:  # noqa: D106
        model = User
        fields = ["username", "email"]

    def clean_email(self):  # noqa: D102
        value = User.objects.normalize_email(self.cleaned_data["email"]).lower()
        try:
            existing_user = User.objects.get(email=value)
        except User.DoesNotExist:
            return value
        if existing_user.pk != self.instance.pk:
            raise ValidationError(_("A user with this email already exists."))
        return value

    def clean_username(self):  # noqa: D102
        return User.normalize_username(self.cleaned_data["username"]).lower()

src/apps/accounts/views.py
from django.shortcuts import redirect
from .forms import SignUpForm, ProfileUpdateForm
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView
from django.views.generic.edit import FormView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import View
from django.shortcuts import render, get_object_or_404

from apps.organizations.models import Organization


class SignUpView(FormView):  # noqa: D101
    form_class = SignUpForm
    initial = {"key": "value"}
    template_name = "accounts/signup.html"
    success_url = "organizations:index"

    def form_valid(self, form):  # noqa: D102
        user = form.save()
        login(self.request, user)
        messages.success(self.request, _("Your account has been successfully created."))
        slug = self.kwargs.get("slug", None)
        if self.kwargs.get("shared", None) and slug:
            organization = get_object_or_404(Organization, slug__iexact=slug)
            organization.assignees.add(user)
            organization.save()
            return redirect(organization)

        return redirect("organizations:index")

    def dispatch(self, request, *args, **kwargs):  # noqa: D102
        if request.user.is_authenticated:
            return redirect(to="/")
        return super(SignUpView, self).dispatch(request, *args, **kwargs)


class CustomLoginView(LoginView):  # noqa: D101
    initial = {"key": "value"}
    template_name = "accounts/login.html"
    success_url = "organizations:index"

    def dispatch(self, request, *args, **kwargs):  # noqa: D102
        if request.user.is_authenticated:
            return redirect(to="/")
        return super(CustomLoginView, self).dispatch(request, *args, **kwargs)


class ProfileUpdateView(SuccessMessageMixin, UpdateView):  # noqa: D101
    model = User
    form_class = ProfileUpdateForm
    template_name = "accounts/profile.html"
    success_url = reverse_lazy("accounts:profile")
    success_message = _("Your profile data has been updated.")

    def get_success_message(self, cleaned_data):  # noqa: D102
        return self.success_message % cleaned_data

    def get_object(self):  # noqa: D102
        return self.request.user

    def dispatch(self, request, *args, **kwargs):  # noqa: D102
        if not request.user.is_authenticated:
            return redirect(to="accounts:login")
        return super(ProfileUpdateView, self).dispatch(request, *args, **kwargs)


class ProfileOrganizationsView(View):  # noqa: D101
    model = User
    template_name = "accounts/organizations.html"

    def get(self, request):  # noqa: D102
        if not request.user.is_authenticated:
            return redirect(to="accounts:login")

        organizations = Organization.objects.filter(
            assignees__username__iexact=request.user.username
        )

        return render(
            request,
            self.template_name,
            {"organizations": organizations},
        )


class CustomPasswordChangeView(SuccessMessageMixin, PasswordChangeView):  # noqa: D101
    template_name = "accounts/password_change.html"
    success_url = reverse_lazy("accounts:password_reset")
    success_message = _("Your password has been changed.")

    def get_success_message(self, cleaned_data):  # noqa: D102
        return self.success_message % cleaned_data

    def dispatch(self, request, *args, **kwargs):  # noqa: D102
        if not request.user.is_authenticated:
            return redirect(to="accounts:login")
        return super(CustomPasswordChangeView, self).dispatch(request, *args, **kwargs)


class CustomPasswordResetView(PasswordResetView, SuccessMessageMixin):  # noqa: D101
    template_name = "accounts/password_reset.html"
    email_template_name = "accounts/password_reset_email.html"
    success_url = reverse_lazy("accounts:password_reset_done")

    def dispatch(self, request, *args, **kwargs):  # noqa: D102
        if request.user.is_authenticated:
            return redirect(to="accounts:password_change")
        return super(CustomPasswordResetView, self).dispatch(request, *args, **kwargs)


class AccountDeleteView(SuccessMessageMixin, DeleteView):  # noqa: D101
    model = User
    template_name = "accounts/delete.html"
    success_url = reverse_lazy("accounts:login")
    success_message = _("Your account has been deleted.")

    def get_success_message(self, cleaned_data):  # noqa: D102
        return self.success_message % cleaned_data

    def get_object(self):  # noqa: D102
        return self.request.user

    def dispatch(self, request, *args, **kwargs):  # noqa: D102
        if not request.user.is_authenticated:
            return redirect(to="accounts:login")
        return super(AccountDeleteView, self).dispatch(request, *args, **kwargs)

src/apps/accounts/templates/accounts/delete.html
{% url 'accounts:profile' as profile_url %}
{% include "accounts/partials/account_forms.html" with description=_("Are you sure you want to delete your account?") form=form help_text=False heading=_("Delete account") button_label=_("Delete account") alt_action_url=profile_url alt_action_text=_("Take me back") %}

src/apps/accounts/templates/accounts/login.html
{% url 'accounts:signup' as signup_url %}
{% include "accounts/partials/account_forms.html" with form=form help_text=False type="login" heading=_("Log in") button_label=_("Log in") alt_action_url=signup_url alt_action_text=_("Create an account") %}

src/apps/accounts/templates/accounts/organizations.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="mx-auto">
        <h2 class="mt-6 text-center text-3xl font-extrabold">{% translate "My organizations" %}</h2>
        <div class="text-center py-6 px-4 sm:px-6 lg:px-8">
            {% translate "The following organizations are connected to your account." %}
        </div>
        <div class="flex items-center justify-center py-6 px-4 sm:px-6 lg:px-8">
            <ul class="mt-6 w-full md:w-1/2 space-y-6">
                {% for organization in organizations %}
                    <li>
                        <a href="{{ organization.get_absolute_url }}">
                            <div class="flex flex-wrap items-center px-4 py-4 sm:px-6 bg-primary-800 hover:bg-primary-400 rounded-lg">
                                <h3 class="text-lg leading-6 font-bold text-white">
                                    {{ organization.name }}
                                    {% if organization.superorganization %}
                                        {% if organization.superorganization.alternative_name %}
                                            [{{ organization.superorganization.alternative_name }}]
                                        {% else %}
                                            [{{ organization.superorganization.name }}]
                                        {% endif %}
                                    {% endif %}
                                </h3>
                                <span class="ml-auto text-md text-white">
                                    {% if organization.state == "approved" %}
                                        ({% translate "Public" %})
                                    {% else %}
                                        ({% translate "Not yet reviewed" %})
                                    {% endif %}
                                </span>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

src/apps/accounts/templates/accounts/password_change.html
{% include "accounts/partials/account_forms.html" with form=form help_text=False heading=_("Change password") button_label=_("Change password") %}

src/apps/accounts/templates/accounts/password_reset.html
{% url 'accounts:login' as login_url %}
{% include "accounts/partials/account_forms.html" with form=form help_text=False heading=_("Reset password") button_label=_("Send reset instructions") alt_action_url=login_url alt_action_text=_("Login") %}

src/apps/accounts/templates/accounts/password_reset_complete.html
{% url 'accounts:login' as login_url %}
{% include "accounts/partials/account_forms.html" with description=_(" Your new password has been set. You can now login.") help_text=False heading=_("Password reset complete") alt_action_url=login_url alt_action_text=_("Login") %}

src/apps/accounts/templates/accounts/password_reset_confirm.html
{% load i18n %}
{% if validlink %}
    {% blocktranslate asvar heading with name=form.user.username %} Reset password for {{ name }} {% endblocktranslate %}
    {% include "accounts/partials/account_forms.html" with form=form help_text=False heading=heading button_label=_("Change password") %}
{% else %}
    {% url 'accounts:password_reset' as pw_reset_url %}
    {% include "accounts/partials/account_forms.html" with description=_(" This password reset link is invalid. Please submit a new reset.") help_text=False heading=_("Reset password") alt_action_url=pw_reset_url alt_action_text=_("Submit new reset") %}
{% endif %}

src/apps/accounts/templates/accounts/password_reset_done.html
{% include "accounts/partials/account_forms.html" with form=False description=_("We've emailed you instructions for setting your password. Please check your inbox, if the email address is correct you should receive the email shortly!") help_text=False heading=_("Password reset email sent") %}

src/apps/accounts/templates/accounts/password_reset_email.html
{# djlint:off #}{% load i18n %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% blocktranslate with name=user.get_username %}Please go to the following page and choose a new password for the user {{name}}:{% endblocktranslate %}
{% block reset_link %}
    https://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock reset_link %}
{% translate "Thanks for using our site!" %}
{# djlint:on #}

src/apps/accounts/templates/accounts/profile.html
{% url 'accounts:delete' as delete_url %}
{% include "accounts/partials/account_forms.html" with form=form help_text=True heading=_("Profile") button_label=_("Update profile") alt_action_url=delete_url alt_action_text=_("Delete account") %}

src/apps/accounts/templates/accounts/signup.html
{% url 'accounts:login' as login_url %}
{% include "accounts/partials/account_forms.html" with form=form help_text=False heading=_("Sign up") button_label=_("Sign Up") alt_action_url=login_url alt_action_text=_("Log in with existing account") %}