src/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from .views import (
    SignUpView,
    CustomLoginView,
    ProfileUpdateView,
    CustomPasswordChangeView,
    CustomPasswordResetView,
    AccountDeleteView,
    ProfileOrganizationsView,
)
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("signup/<slug>/", SignUpView.as_view(), name="signup"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "profile/",
        ProfileUpdateView.as_view(),
        name="profile",
    ),
    path(
        "organizations/",
        ProfileOrganizationsView.as_view(),
        name="profile_organizations",
    ),
    path(
        "password_change/",
        CustomPasswordChangeView.as_view(template_name="accounts/password_change.html"),
        name="password_change",
    ),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "delete",
        AccountDeleteView.as_view(template_name="accounts/delete.html"),
        name="delete",
    ),
]

src/apps/theme/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

app_name = "theme"

urlpatterns = [
    path(
        "language_picker.html",
        TemplateView.as_view(
            template_name="partials/language_picker.html",
            content_type="text/html; charset=utf-8",
        ),
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "site.webmanifest",
        TemplateView.as_view(
            template_name="site.webmanifest", content_type="application/manifest+json"
        ),
    ),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from apps.organizations.sitemap import OrganizationSitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap


urlpatterns = [
    path("admin/", admin.site.urls),
    path("filters/", include("apps.filtercategories.urls")),
    path("", include("apps.organizations.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("accounts/", include("apps.accounts.urls")),
    path("locations/", include("apps.locations.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("apps.theme.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "organizations": OrganizationSitemap,
                "flatpages": FlatPageSitemap,
            }
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/theme/templates/partials/advanced_select.html
{% comment %}
    Component:  preline-advanced-select
    Docs:       https://preline.co/docs/advanced-select.html
    Widget:     AdvancedSelect
{% endcomment %}
{# djlint:off #}
<select multiple=""
        data-hs-select='{
            "placeholder": "Select option...",
            "dropdownClasses": "mt-2 z-50 w-full max-h-72 p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-track]:bg-gray-100 [&::-webkit-scrollbar-thumb]:bg-gray-300 dark:[&::-webkit-scrollbar-track]:bg-neutral-700 dark:[&::-webkit-scrollbar-thumb]:bg-neutral-500 dark:bg-neutral-900 dark:border-neutral-700",
            "optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 dark:bg-neutral-900 dark:hover:bg-neutral-800 dark:text-neutral-200 dark:focus:bg-neutral-800",
            "mode": "tags",
            "wrapperClasses": "relative ps-0.5 pe-9 min-h-[46px] flex items-center flex-wrap text-nowrap w-full border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400",
            "tagsItemTemplate": "<div class=\"flex flex-nowrap items-center relative z-10 bg-white border border-gray-200 rounded-full p-1 m-1 dark:bg-neutral-900 dark:border-neutral-700 \"><div class=\"whitespace-nowrap text-gray-800 dark:text-neutral-200 ms-2 \" data-title></div><div class=\"inline-flex shrink-0 justify-center items-center size-5 ms-2 rounded-full text-gray-800 bg-gray-200 hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-400 text-sm dark:bg-neutral-700/50 dark:hover:bg-neutral-700 dark:text-neutral-400 cursor-pointer\" data-remove><svg class=\"shrink-0 size-3\" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 6 6 18\"/><path d=\"m6 6 12 12\"/></svg></div></div>",
            "tagsInputId": "hs-tags-input-{{ widget.name }}",
            "tagsInputClasses": "focus:ring-0 border-0 py-3 px-2 rounded-lg order-1 text-sm outline-none dark:bg-neutral-900 dark:placeholder-neutral-500 dark:text-neutral-400",
            "optionTemplate": "<div class=\"flex items-center\"><div data-icon></div><div><div class=\"text-sm font-semibold text-gray-800 dark:text-neutral-200 \" data-title></div><div class=\"text-xs text-gray-500 dark:text-neutral-500 text-wrap \" data-description></div></div><div class=\"ms-auto\"><span class=\"hidden hs-selected:block\"><svg class=\"shrink-0 size-4 text-blue-600\" xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\"><path d=\"M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z\"/></svg></span></div></div>",
            "extraMarkup": "<div class=\"absolute top-1/2 end-3 -translate-y-1/2\"><svg class=\"shrink-0 size-3.5 text-gray-500 dark:text-neutral-500 \" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m7 15 5 5 5-5\"/><path d=\"m7 9 5-5 5 5\"/></svg></div>",
            "isAddTagOnEnter": false
        }'
        name="{{ widget.name }}"
        {% include "django/forms/widgets/attrs.html" %}
        class="hidden"
        x-init="() => {waitForElm('#hs-tags-input-{{ widget.name }}').then((e) => {e.autofocus = true})}">
{# djlint:on #}
{% for group_name, group_choices, group_index in widget.optgroups %}
    {% for option in group_choices %}
        <option value="{{ option.value|stringformat:'s' }}"
                {% include "django/forms/widgets/attrs.html" with widget=option %}
                data-hs-select-option='{ "description": "{{ option.description|escapejs }}" }'>
            {{ option.label }}
        </option>
    {% endfor %}
{% endfor %}
</select>

src/apps/theme/templates/partials/button_group-view_toggle.html
{% comment %}
    Component:  button-group
    Docs:       https://preline.co/docs/button-group.html
{% endcomment %}
<div class="flex sm:inline-flex flex-row rounded-lg shadow-sm">
    <button type="button"
            class="py-1.5 px-4 inline-flex items-center gap-x-2 first:rounded-s-lg sm:mt-0 sm:first:ms-0 first:rounded-se-none last:rounded-es-none last:rounded-e-lg text-sm font-medium focus:z-10 border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 focus:outline-none focus:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
            hx-push-url="true"
            hx-target="#results-container"
            hx-include="#radarini-filter"
            hx-get="/list/">{% include 'icons/bars-3-center-left.html' with style="size-4" %}</button>
    <button type="button"
            class="py-1.5 px-4 inline-flex items-center gap-x-2 first:rounded-s-lg sm:mt-0 sm:first:ms-0 first:rounded-se-none last:rounded-es-none last:rounded-e-lg text-sm font-medium focus:z-10 border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 focus:outline-none focus:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
            hx-push-url="true"
            hx-target="#results-container"
            hx-include="#radarini-filter"
            hx-get="/map/">{% include 'icons/map.html' with style="size-4" %}</button>
</div>

src/apps/theme/templates/partials/button_link.html
<a href="{{ href }}"
   class="{{ width }} py-2 px-4 font-medium text-white bg-primary-800 hover:bg-primary-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-800">
    {{ label }}
</a>

src/apps/theme/templates/partials/language_picker.html
{% load i18n %}
<form action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <input name="next" type="hidden" value="">
    <select name="language"
            autofocus
            onchange="this.form.submit()"
            id="language_picker"
            role="listbox"
            aria-label="{% trans 'Language selection' %}"
            class="select select-sm font-normal text-base bg-inherit rounded border-0 shadow-none py-0">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"
                    {% if language.code == LANGUAGE_CODE %}selected{% endif %}>{{ language.name_local }}</option>
        {% endfor %}
    </select>
</form>

src/apps/theme/templates/partials/modal-button-language_picker.html
{% comment %}
    Component:  modal (button with icon)
    Docs:       https://preline.co/docs/modal.html
    Input:     {'id':'foo'}
{% endcomment %}
<button type="button"
        class="size-7 flex justify-center items-center gap-x-2 rounded-lg border border-slate-200 bg-white text-slate-800 shadow-sm hover:bg-slate-50 focus:outline-none focus:bg-slate-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-transparent dark:border-slate-700 dark:text-white dark:hover:bg-white/10 dark:focus:bg-white/10"
        aria-haspopup="dialog"
        aria-expanded="false"
        aria-controls="{{ id }}-modal"
        data-hs-overlay="#{{ id }}-modal">
    {% include 'icons/language.html' with style="size-4" stroke_width="2" %}
</button>

src/apps/theme/templates/partials/modal-button.html
{% comment %}
    Component:  modal (button with indicator)
    Docs:       https://preline.co/docs/modal.html
    Input:     {'id':'foo', 'button_text':'bar'}
{% endcomment %}
<button type="button"
        class="py-1.5 px-3 inline-flex items-center gap-x-2 font-medium rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 focus:outline-none focus:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none"
        aria-haspopup="dialog"
        aria-expanded="false"
        aria-controls="{{ id }}-modal"
        data-hs-overlay="#{{ id }}-modal">
    {{ button_text }}
    <span id="{{ id }}-button-indicator"
          class="inline-flex items-center py-0.5 px-1.5 rounded-full text-sm font-medium bg-secondary-800"></span>
</button>

src/apps/theme/templates/partials/modal-dialog.html
{% comment %}
    Component:  modal (dialog)
    Docs:       https://preline.co/docs/modal.html
    Input:      {'id':'foo', 'dialog_title':'bar', 'dialog_content': 'foobar', dialog_content_include: 'path/to/file.html'}
{% endcomment %}
<div id="{{ id }}-modal"
     class="hs-overlay hidden size-full fixed top-0 start-0 z-[60] overflow-x-hidden overflow-y-auto pointer-events-none"
     role="dialog"
     tabindex="-1"
     aria-labelledby="{{ id }}-modal-label">
    <div class="sm:max-w-lg sm:w-full m-3 sm:mx-auto">
        <div class="flex flex-col bg-white border shadow-sm rounded-xl pointer-events-auto dark:bg-neutral-800 dark:border-neutral-700 dark:shadow-neutral-700/70">
            <div class="flex justify-between items-center py-3 px-4 border-b dark:border-neutral-700">
                <h3 id="{{ id }}-modal-label"
                    class="font-bold text-gray-800 dark:text-white">{{ dialog_title }}</h3>
                <button type="button"
                        class="size-8 inline-flex justify-center items-center gap-x-2 rounded-full border border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200 focus:outline-none focus:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-700 dark:hover:bg-neutral-600 dark:text-neutral-400 dark:focus:bg-neutral-600"
                        aria-label="Close"
                        data-hs-overlay="#{{ id }}-modal">
                    <span class="sr-only">Close</span>
                    <svg class="shrink-0 size-4"
                         xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         fill="none"
                         stroke="currentColor"
                         stroke-width="2"
                         stroke-linecap="round"
                         stroke-linejoin="round">
                        <path d="M18 6 6 18"></path>
                        <path d="m6 6 12 12"></path>
                    </svg>
                </button>
            </div>
            <div class="p-4">
                {% if dialog_content %}
                    {{ dialog_content }}
                {% elif dialog_content_include %}
                    {% include dialog_content_include %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

src/apps/theme/templates/partials/navbar.html
{% load static i18n parler_tags %}
{% with req=request.path v_name=request.resolver_match.view_name %}
    <nav class="w-full flex-row mx-auto sm:flex sm:flex-row sm:items-center sm:justify-between text-xl tracking-wide">
        <div class="flex items-center justify-between">
            <a href="/" class="flex flex-row" aria-label="Brand">
                <span class="w-max inline-flex items-center gap-x-2 text-3xl focus:outline-none focus:opacity-80">
                    <img src="{% static 'images/logo.svg' %}"
                         class="mr-3 xl:h-24 xl:w-12 xl:-left-28 xl:top-5 xl:block xl:absolute"
                         alt="Logo of the {{ site.settings|get_translated_field:'title' }} site."
                         height="96"
                         width="24" />
                    {{ site.settings|get_translated_field:'title'|upper }}
                </span>
            </a>
            <div class="sm:hidden flex flex-row">
                <button type="button"
                        class="hs-collapse-toggle relative size-7 flex justify-center items-center gap-x-2 rounded-lg border border-slate-200 bg-white text-slate-800 shadow-sm hover:bg-slate-50 focus:outline-none focus:bg-slate-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-transparent dark:border-slate-700 dark:text-white dark:hover:bg-white/10 dark:focus:bg-white/10"
                        id="hs-navbar-collapse"
                        aria-expanded="false"
                        aria-controls="hs-navbar"
                        aria-label="Toggle navigation"
                        data-hs-collapse="#hs-navbar">
                    <svg class="hs-collapse-open:hidden shrink-0 size-4"
                         xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         fill="none"
                         stroke="currentColor"
                         stroke-width="2"
                         stroke-linecap="round"
                         stroke-linejoin="round">
                        <line x1="3" x2="21" y1="6" y2="6" /><line x1="3" x2="21" y1="12" y2="12" /><line x1="3" x2="21" y1="18" y2="18" />
                    </svg>
                    <svg class="hs-collapse-open:block hidden shrink-0 size-4"
                         xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         fill="none"
                         stroke="currentColor"
                         stroke-width="2"
                         stroke-linecap="round"
                         stroke-linejoin="round">
                        <path d="M18 6 6 18" />
                        <path d="m6 6 12 12" />
                    </svg>
                    <span class="sr-only">Toggle navigation</span>
                </button>
            </div>
        </div>
        <div id="hs-navbar"
             class="hidden hs-collapse overflow-hidden transition-all duration-300 basis-full grow sm:block mt-4 sm:mt-0"
             aria-labelledby="hs-navbar-collapse">
            <div class="flex flex-col gap-2 sm:gap-5 sm:flex-row sm:items-center sm:justify-end sm:ps-5">
                <a class="main-menu-link {% if req == '/' %}bg-secondary-800 text-white{% endif %}"
                   href="/"
                   {% if req == '/' or  req == '/list/' or  req == '/map/' %}aria-current="page"{% endif %}>{% translate "Search" %}</a>
                <a class="main-menu-link {% if v_name == 'organizations:submit-organization' %}bg-secondary-800 text-white{% endif %}"
                   href="{% url "organizations:submit-organization" %}"
                   {% if v_name == 'organizations:submit-organization' %}aria-current="page"{% endif %}>{% translate "Propose entry" %}</a>
                <a class="main-menu-link {% if req == '/participate/' %}bg-secondary-800 text-white{% endif %}"
                   href="/participate/"
                   {% if req == '/participate/' %}aria-current="page"{% endif %}>{% translate "Participate" %}</a>
                <a class="main-menu-link {% if req == '/contact/' %}bg-secondary-800 text-white{% endif %}"
                   href="/contact/"
                   {% if req == '/contact/' %}aria-current="page"{% endif %}>{% translate "Contact" %}</a>
                <div class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none]">
                    <button id="hs-navbar-dropdown"
                            type="button"
                            class="hs-dropdown-toggle flex items-center w-full font-medium main-menu-link {% if req == '/idea/' or req == '/financing/' or req == '/about/' or req == '/cooperations/' %}bg-secondary-800 text-white{% endif %}"
                            aria-haspopup="menu"
                            aria-expanded="false"
                            aria-label="Mega Menu">
                        {% translate "The project" %}
                        <svg class="hs-dropdown-open:-rotate-180 sm:hs-dropdown-open:rotate-0 duration-300 ms-1 shrink-0 size-4"
                             xmlns="http://www.w3.org/2000/svg"
                             width="24"
                             height="24"
                             viewBox="0 0 24 24"
                             fill="none"
                             stroke="currentColor"
                             stroke-width="2"
                             stroke-linecap="round"
                             stroke-linejoin="round">
                            <path d="m6 9 6 6 6-6" />
                        </svg>
                    </button>
                    <div class="hs-dropdown-menu z-10 transition-[opacity,margin] ease-in-out duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 sm:shadow-md rounded-lg p-1 space-y-1 before:absolute top-full sm:border before:-top-5 before:start-0 before:w-full before:h-5 hidden bg-base-100 border-primary-800"
                         role="menu"
                         aria-orientation="vertical"
                         aria-labelledby="hs-navbar-dropdown">
                        <a class="flex items-center gap-x-3.5 main-menu-link" href="/idea/">{% translate "Idea" %}</a>
                        <a class="flex items-center gap-x-3.5 main-menu-link" href="/financing/">{% translate "Financing" %}</a>
                        <a class="flex items-center gap-x-3.5 main-menu-link" href="/donate/">{% translate "Donate" %}</a>
                        <a class="flex items-center gap-x-3.5 main-menu-link" href="/about/">{% translate "About Us" %}</a>
                        <a class="flex items-center gap-x-3.5 main-menu-link"
                           href="/cooperations/">{% translate "Cooperations" %}</a>
                    </div>
                </div>
                {% if user.is_authenticated %}
                    <div class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none]">
                        <button id="hs-navbar-dropdown"
                                type="button"
                                class="hs-dropdown-toggle flex items-center w-full font-medium main-menu-link  {% if v_name == 'accounts:profile' or v_name == 'organizations:dashboard' or v_name == 'accounts:profile_organizations' or v_name == 'accounts:password_change' %} bg-secondary-800 text-white{% endif %}"
                                aria-haspopup="menu"
                                aria-expanded="false"
                                aria-label="Mega Menu">
                            {% translate "Account" %}
                            <svg class="hs-dropdown-open:-rotate-180 sm:hs-dropdown-open:rotate-0 duration-300 ms-1 shrink-0 size-4"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="24"
                                 height="24"
                                 viewBox="0 0 24 24"
                                 fill="none"
                                 stroke="currentColor"
                                 stroke-width="2"
                                 stroke-linecap="round"
                                 stroke-linejoin="round">
                                <path d="m6 9 6 6 6-6" />
                            </svg>
                        </button>
                        <div class="hs-dropdown-menu z-10 transition-[opacity,margin] ease-in-out duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 sm:shadow-md rounded-lg p-1 space-y-1 before:absolute top-full sm:border before:-top-5 before:start-0 before:w-full before:h-5 hidden bg-base-100 border-primary-800"
                             role="menu"
                             aria-orientation="vertical"
                             aria-labelledby="hs-navbar-dropdown">
                            <a class="flex items-center gap-x-3.5 main-menu-link"
                               href="{% url 'accounts:profile' %}">{% translate "My Profile" %}</a>
                            {% if user.is_staff %}
                                <a class="flex items-center gap-x-3.5 main-menu-link"
                                   href="{% url 'organizations:dashboard' %}">{% translate "Organization Dashboard" %}</a>
                            {% endif %}
                            <a class="flex items-center gap-x-3.5 main-menu-link"
                               href="{% url 'accounts:profile_organizations' %}">{% translate "My Organizations" %}</a>
                            <a class="flex items-center gap-x-3.5 main-menu-link"
                               href="{% url 'accounts:password_change' %}">{% translate "Change Password" %}</a>
                            <form method="post"
                                  action="{% url 'accounts:logout' %}"
                                  class="main-menu-link">
                                {% csrf_token %}
                                <button type="submit">{% translate "Logout" %}</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
                <div class="flex flex-row gap-1">
                    {% include "partials/theme_toggle.html" %}
                    {% with "language-picker" as id and "Language picker" as dialog_title and '<div hx-get="/language_picker.html" hx-trigger="load"></div>' as dialog_content %}
                    {% include "partials/modal-button-language_picker.html" %}
                    {% include "partials/modal-dialog.html" %}
                {% endwith %}
            </div>
        </div>
    </div>
</nav>
{% endwith %}

src/apps/theme/templates/partials/noscript.html
{% load static i18n parler_tags %}
<style>
    [x-cloak] { display: inherit !important; }
    [hidden-no-js] { display: none !important; }
</style>
<div class="h-48 sm:h-36 md:h-32"></div>
<div class="my-4 py-8 px-4 bg-red-200 rounded-md absolute top-2 z-50">
    <p class="text-red-800 ">
        {% translate "For full functionality of this site it is necessary to enable JavaScript. Here are the " %}<a class="text-black underline"
   href="https://www.enable-javascript.com/">instructions</a> {% translate "how to enable JavaScript in your web browser." %}
    </p>
</div>

src/apps/theme/templates/partials/profile-header.html
{% load i18n %}
{% if user.is_authenticated %}
    <div class="flex gap-2">
        <div>{% translate 'Hi' %}, {{ user.username }}</div>
        <div>{% include "partials/button_link.html" with label=_("Log out") href="/users/logout" %}</div>
    </div>
{% endif %}

src/apps/theme/templates/partials/text_field.html
<div class="{{ width }} flex-grow flex flex-col">
    <label class="block font-medium">
        {{ field.label }}
        {% if field.field.required %}*{% endif %}
        {{ field }}
    </label>
    <p class="helptext">{{ field.help_text|safe }}</p>
    <p class="text-red-600">{{ field.errors }}</p>
</div>